version: 2
registries:
  pylance-azure-npm-feed:
    type: npm-registry
    url: https://pkgs.dev.azure.com/devdiv/_packaging/Pylance/npm/registry
    token: ${{ secrets.NPM_PRIVATE_REG_TOKEN }}

updates:
  - package-ecosystem: 'npm'
    directory: ''
    registries:
      - pylance-azure-npm-feed
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Build/16.0'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Build/17.0'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Common/Tests/MockVsTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Common/Tests/SccPackage'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Common/Tests/Utilities'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Common/Tests/Utilities.UI'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Common/Tools/BuildTasks'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Attacher'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/AttacherX86'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/BuildTasks'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Common'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Cookiecutter'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Core'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Debugger'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Debugger.Concord'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Django'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/EnvironmentsList'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Ipc.Json'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Profiling'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/ProjectWizards'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/PythonTools'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/RunElevated'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/TestAdapter'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/TestAdapter.Executor'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/VCDebugLauncher'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/VSCommon'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/VSInterpreters'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/WebRole'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Product/Workspace'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Templates'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/CookiecutterTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/Core'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/Core.UI'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/DebuggerTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/DebuggerUITests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/DebuggerUITestsRunner'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/DjangoTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/DjangoUITests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/DjangoUITestsRunner'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/FastCgi'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/ProfilingTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/ProfilingUITests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/ProfilingUITestsRunner'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/ProjectUITests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/ProjectUITestsRunner'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/PythonToolsMockTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/PythonToolsUITestsRunner'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/ReplWindowUITests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/ReplWindowUITestsRunner'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/TestAdapterTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/TestData/AddProjectReference/ClassLibrary'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/TestData/ConsoleApplication1'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/TestData/ProjectReference/ClassLibrary'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/TestRunnerInterop'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/Utilities.Python'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/Utilities.Python.Analysis'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Python/Tests/VSInterpretersTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Templates/Django/ProjectTemplates/Python/Web/DjangoProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Templates/Django/ProjectTemplates/Python/Web/StarterDjangoProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Templates/Web/ProjectTemplates/Python/Web/StarterBottleProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskJadeProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Templates/Web/ProjectTemplates/Python/Web/StarterFlaskProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Templates/Web/ProjectTemplates/Python/Web/WebProjectBottle'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Templates/Web/ProjectTemplates/Python/Web/WebProjectFlask'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Tests/TestData/Cookiecutter/template_requirementstxt/{{cookiecutter.project_slug}}'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Tests/TestData/InfoBar/InfoBarMissingPackages'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'pip'
    directory: 'Python/Tests/TestData/InfoBar/InfoBarReqsTxt'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

# Built with ‚ù§ by [Pipeline Foundation](https://pipeline.foundation)
